# Use official Node.js image
FROM node:18

# Set working directory in container
WORKDIR /usr/src/app

# Copy only package.json files first (to cache deps)
COPY src/femail-web/package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the React app
COPY ./src/femail-web/ ./

# Expose the port the React dev server runs on (default is 3000)
EXPOSE 3000

# Start the React dev server
CMD ["npm", "start"]
