# Use an official Python base image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy the client script into the container
COPY src/blacklist/Client.py .

# Run the script with arguments (set in runtime)
ENTRYPOINT ["python", "Client.py"]
